-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#333333'
local Color4 = '#18b5e4'
local Color6 = '#d1ccf1'
local Color0 = '#bea17f'
local Color3 = '#eee385'
local Color1 = '#dd5555'
local Color2 = '#5ac16c'
local Color7 = '#2f2f2f'
local Color8 = '#4b4b4b'
local Color9 = '#d2cdf2'

highlight('Comment', nil, Color0, 'italic')
highlight('Operator', nil, Color1, nil)
highlight('Conditional', nil, Color1, nil)
highlight('Repeat', nil, Color1, nil)
highlight('String', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('StatusLine', nil, Color5, nil)
highlight('WildMenu', Color7, Color6, nil)
highlight('Pmenu', Color7, Color6, nil)
highlight('PmenuSel', Color6, Color8, nil)
highlight('PmenuThumb', Color7, Color6, nil)
highlight('Normal', Color7, Color6, nil)
highlight('Visual', Color8, nil, nil)
highlight('CursorLine', Color8, nil, nil)
highlight('ColorColumn', Color8, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('TabLineSel', Color9, Color8, nil)
highlight('TSPunctDelimiter', nil, Color6, nil)

link('Conditional', 'Operator')
link('TSParameterReference', 'TSParameter')
link('TSConstant', 'Constant')
link('TSFunction', 'Function')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSLabel', 'Type')
link('TSNamespace', 'TSType')
link('TSRepeat', 'Repeat')
link('TSString', 'String')
link('TSNumber', 'Number')
link('TSFloat', 'Number')
link('Macro', 'Function')
link('TSField', 'Constant')
link('Whitespace', 'Comment')
link('Operator', 'Keyword')
link('TSTagDelimiter', 'Type')
link('TSKeyword', 'Keyword')
link('TSConditional', 'Conditional')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('TSParameter', 'Constant')
link('TSFuncMacro', 'Macro')
link('TSOperator', 'Operator')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('NonText', 'Comment')
link('TSType', 'Type')
link('TSComment', 'Comment')
link('TSTag', 'MyTag')
link('TSProperty', 'TSField')
link('TSPunctBracket', 'MyTag')
